data:
  root: './data/1024px_pngs'
  batch_size: 8
  training_size: 3000
  total_size: 3500
  image_size: 1024

experiments:
  root: './experiments/6.0'
  model_path: "autoencoder.pth"
  results_dir: "results"
  logs_dir: "logs"
  analysis_path: "analysis.png"

compression:
  algorithm: zlib
  quality: 9

training:
  epochs: 10
  learning_rate: 0.0001