# Configuration file for the reconstruction system
data:
  root: './data/1024px_pngs'
  batch_size: 4
  subset_size: 3000
  image_size: 1024

experiments:
  root: './experiments/5.1[524288]'
  model_path: "autoencoder.pth"
  results_dir: "results"
  logs_dir: "logs"
  analysis_path: "analysis.png"

compression:
  algorithm: zlib
  quality: 9

training:
  epochs: 10
  learning_rate: 0.001